import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { discoverAgents, discoverMcps, discoverPlugins, discoverSkills, deleteResource, renameAgent, renameMcpAcrossScopes, renameSkill, setMcpState, setPluginEnabled, setSkillEnabled, transferResources } from "../src/index.js";

async function fixture() {
  const root = await mkdtemp(join(tmpdir(), "codex-powertoys-")); const home = join(root, "home"); const codex = join(home, ".codex"); const workspace = join(root, "workspace");
  await mkdir(join(home, ".agents", "skills", "alpha", "agents"), { recursive: true }); await mkdir(join(workspace, ".agents", "skills", "alpha"), { recursive: true }); await mkdir(join(codex, "plugins", "cache", "source", "plugin", "1.0.0", ".codex-plugin"), { recursive: true }); await mkdir(join(codex, "plugins", "cache", "source", "plugin", "1.0.0", "skills", "alpha"), { recursive: true }); await mkdir(join(codex, "plugins", "cache", "remote-source", "remote-plugin"), { recursive: true }); await mkdir(join(workspace, ".codex"), { recursive: true });
  await writeFile(join(home, ".agents", "skills", "alpha", "SKILL.md"), "---\nname: alpha\ndescription: Global\n---\nGlobal skill\n"); await writeFile(join(home, ".agents", "skills", "alpha", "agents", "openai.yaml"), "interface:\n  display_name: Alpha\n  short_description: Alpha skill\n"); await writeFile(join(workspace, ".agents", "skills", "alpha", "SKILL.md"), "---\nname: alpha\n---\nWorkspace skill\n"); const pluginRoot = join(codex, "plugins", "cache", "source", "plugin", "1.0.0"); const pluginSkill = join(pluginRoot, "skills", "alpha", "SKILL.md"); await writeFile(pluginSkill, "---\nname: alpha\n---\nPlugin skill\n"); await writeFile(join(pluginRoot, ".codex-plugin", "plugin.json"), JSON.stringify({ name: "plugin", version: "1.0.0", skills: "./skills", mcpServers: "./plugin-mcp.json" })); await writeFile(join(pluginRoot, "plugin-mcp.json"), JSON.stringify({ mcpServers: { pluginServer: { command: "echo", args: ["plugin"], cwd: "." } } })); await writeFile(join(codex, "plugins", "cache", "remote-source", "remote-plugin", ".codex-remote-plugin-install.json"), JSON.stringify({ schema_version: 1, remote_plugin_id: "remote-id" })); await writeFile(join(codex, "config.toml"), `[plugins."plugin@source"]\nenabled = false\n\n[mcp_servers.test]\ncommand = "echo"\nargs = ["hello"]\n\n[mcp_servers.test.env]\nTOKEN = "secret"\n`); await writeFile(join(workspace, ".codex", "config.toml"), "");
  return { root, home, codex, workspace };
}

test("discovers skills, metadata, and duplicate shadowing", async () => {
  const values = await fixture(); const result = await discoverSkills({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }); const alpha = result.skills.filter((skill) => skill.name === "alpha"); assert.equal(alpha.length, 3); assert.equal(alpha.some((skill) => skill.state.effective === "active"), true); assert.equal(alpha.some((skill) => skill.metadata?.displayName === "Alpha"), true); assert.equal(alpha.some((skill) => skill.state.effective === "unavailable"), true);
});

test("malformed optional metadata remains visible with a diagnostic", async () => {
  const values = await fixture(); const directory = join(values.home, ".agents", "skills", "broken", "agents"); await mkdir(directory, { recursive: true }); await writeFile(join(values.home, ".agents", "skills", "broken", "SKILL.md"), "Broken skill\n"); await writeFile(join(directory, "openai.yaml"), "interface: [\n");
  const result = await discoverSkills({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }); const broken = result.skills.find((skill) => skill.name === "broken"); assert.ok(broken); assert.ok(broken.diagnostics.some((diagnostic) => diagnostic.code === "SKILL_METADATA_INVALID"));
});

test("skill disable and reset preserve unrelated config", async () => {
  const values = await fixture(); const global = join(values.codex, "config.toml"); await setSkillEnabled({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }, join(values.home, ".agents", "skills", "alpha", "SKILL.md"), "global", false); let text = await readFile(global, "utf8"); assert.match(text, /enabled = false/); assert.match(text, /mcp_servers\.test/); await setSkillEnabled({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }, join(values.home, ".agents", "skills", "alpha", "SKILL.md"), "global", true); text = await readFile(global, "utf8"); assert.doesNotMatch(text, /skills\.config/); assert.match(text, /mcp_servers\.test/);
});

test("discovers MCP nested config and mutates only enabled", async () => {
  const values = await fixture(); const result = await discoverMcps({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }); const testMcp = result.mcps.find((item) => item.name === "test"); assert.equal(testMcp?.name, "test"); assert.deepEqual(testMcp?.config.args, ["hello"]); assert.deepEqual(testMcp?.config.env, { TOKEN: "secret" }); await setMcpState({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }, "global", "test", false); const text = await readFile(join(values.codex, "config.toml"), "utf8"); assert.match(text, /enabled = false/); assert.match(text, /command = "echo"/); assert.match(text, /TOKEN = "secret"/);
});

test("discovers plugins and disables their skills and MCPs", async () => {
  const values = await fixture(); const plugins = await discoverPlugins({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }); const plugin = plugins.plugins.find((item) => item.name === "plugin"); assert.ok(plugin); assert.equal(plugin.enabled, false); assert.equal(plugin.skillPaths.length, 1); assert.deepEqual(plugin.mcpNames, ["pluginServer"]); const mcps = await discoverMcps({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }); assert.equal(mcps.mcps.find((item) => item.name === "pluginServer")?.effective, "unavailable"); const skills = await discoverSkills({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }); assert.equal(skills.skills.find((item) => item.sourceKind === "plugin")?.state.effective, "unavailable"); await setPluginEnabled({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }, plugin, true, "global"); assert.match(await readFile(join(values.codex, "config.toml"), "utf8"), /enabled = true/); await setPluginEnabled({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }, plugin, undefined, "global"); assert.doesNotMatch(await readFile(join(values.codex, "config.toml"), "utf8"), /plugins\.\"plugin@source\"/);
});

test("discovers remote-install plugin metadata and declared MCP paths", async () => {
  const values = await fixture(); const result = await discoverPlugins({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }); const remote = result.plugins.find((item) => item.name === "remote-plugin"); assert.equal(remote?.id, "remote-id"); assert.equal(result.plugins.find((item) => item.name === "plugin")?.mcpPath?.endsWith("plugin-mcp.json"), true);
});

test("discovers recursive agents and performs source-aware renames", async () => {
  const values = await fixture(); const nested = join(values.codex, "agents", "team", "reviewer.toml"); await mkdir(join(values.codex, "agents", "team"), { recursive: true }); await writeFile(nested, "name = \"reviewer\"\nmodel = \"gpt\"\n"); const agents = await discoverAgents({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }); assert.equal(agents.agents[0]?.relativePath, "team/reviewer.toml"); await renameAgent({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }, nested, "reviewer-new"); assert.equal((await discoverAgents({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace })).agents[0]?.name, "reviewer-new"); const skillDirectory = join(values.home, ".agents", "skills", "alpha"); await renameSkill({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }, skillDirectory, "alpha-renamed"); assert.match(await readFile(join(values.home, ".agents", "skills", "alpha-renamed", "SKILL.md"), "utf8"), /name: alpha-renamed/);
});

test("handles transfer conflicts, MCP renames, and protected roots", async () => {
  const values = await fixture(); const source = join(values.home, ".agents", "skills", "alpha"); const identity = { kind: "skill" as const, id: "alpha", name: "alpha", scope: "global" as const, path: source, relativePath: "alpha", sourceKind: "user" as const }; const skipped = await transferResources({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }, { resources: [identity], operation: "copy", targetScope: "workspace", conflictMode: "skip" }); assert.equal(skipped.items[0]?.skipped, true); const replaced = await transferResources({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }, { resources: [identity], operation: "copy", targetScope: "workspace", conflictMode: "replace" }); assert.equal(replaced.items[0]?.changed, true); await renameMcpAcrossScopes({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }, "test", "renamed"); assert.match(await readFile(join(values.codex, "config.toml"), "utf8"), /mcp_servers\.renamed/); await assert.rejects(deleteResource({ homeDir: values.home, codexHome: values.codex, workspaceRoot: values.workspace }, { kind: "skill", id: "root", name: "root", scope: "global", path: join(values.home, ".agents", "skills"), sourceKind: "user" }));
});
