#!/usr/bin/env node
import { Command } from "commander";
import { addMcpDefinition, deleteMcpDefinition, deleteResource, discoverAgents, discoverMcps, discoverPlugins, discoverSkills, discoverRoots, loadMcpTools, renameAgent, renameMcpAcrossScopes, renameSkill, setMcpState, setPluginEnabled, setSkillEnabled, transferResources, updateMcpDefinition, type ResourceIdentity, type ResourceKind } from "@codex-powertoys/core";

function options(command: Command): Command { return command.option("--json", "emit JSON output").option("--workspace <path>", "workspace root").option("--codex-home <path>", "Codex home directory"); }
function output(value: unknown, json?: boolean): void { if (json) console.log(JSON.stringify(value, null, 2)); else if (typeof value === "string") console.log(value); else console.dir(value, { depth: 8, colors: true }); }
function discoveryOptions(command: Command) { const opts = command.opts<{ workspace?: string; codexHome?: string }>(); return { workspaceRoot: opts.workspace, codexHome: opts.codexHome }; }

const program = new Command().name("codex-inspect").description("Inspect Codex skills, plugins, agents, and MCP configuration").version("0.1.0");
const roots = options(program.command("roots").description("Show resolved discovery roots")); roots.action(async () => { const opts = discoveryOptions(roots); output(await discoverRoots(opts), roots.opts().json); });
const status = options(program.command("status").description("Show a discovery summary and diagnostics")); status.action(async () => { const opts = discoveryOptions(status); const [rootResult, skillsResult, mcpResult, agentsResult] = await Promise.all([discoverRoots(opts), discoverSkills(opts), discoverMcps(opts), discoverAgents(opts)]); output({ roots: rootResult, skills: { count: skillsResult.skills.length, diagnostics: skillsResult.diagnostics }, mcps: { count: mcpResult.mcps.length, diagnostics: mcpResult.diagnostics }, agents: { count: agentsResult.agents.length, diagnostics: agentsResult.diagnostics } }, status.opts().json); });
const plugins = program.command("plugins").alias("plugin").description("Inspect Codex plugins");
const listPlugins = options(plugins.command("list").description("List discovered plugins")); listPlugins.action(async () => { output(await discoverPlugins(discoveryOptions(listPlugins)), listPlugins.opts().json); });
const showPlugin = options(plugins.command("show <name>").description("Show a plugin")); showPlugin.action(async (name: string) => { const result = await discoverPlugins(discoveryOptions(showPlugin)); const matches = result.plugins.filter((plugin) => plugin.name === name || plugin.id === name || plugin.configKey === name); if (!matches.length) throw new Error(`Plugin not found: ${name}`); output(matches.length === 1 ? matches[0] : matches, showPlugin.opts().json); });
const setPlugin = options(plugins.command("set <name>").requiredOption("--scope <scope>", "global or workspace").option("--disable").option("--enable").option("--reset")).description("Set a plugin override"); setPlugin.action(async (name: string) => { const values = setPlugin.opts(); const result = await discoverPlugins(discoveryOptions(setPlugin)); const plugin = result.plugins.find((item) => item.name === name || item.id === name || item.configKey === name); if (!plugin) throw new Error(`Plugin not found: ${name}`); const enabled = values.reset ? undefined : Boolean(values.enable); output(await setPluginEnabled(discoveryOptions(setPlugin), plugin, enabled, values.scope as "global" | "workspace"), values.json); });
const skills = program.command("skills").description("Inspect skills");
const listSkills = options(skills.command("list").description("List discovered skills")); listSkills.action(async () => { const opts = discoveryOptions(listSkills); const result = await discoverSkills(opts); output({ host: result.roots.hostLabel, skills: result.skills, diagnostics: result.diagnostics }, listSkills.opts().json); });
const showSkill = options(skills.command("show <name>").description("Show a skill and its content")); showSkill.action(async (name: string) => { const result = await discoverSkills(discoveryOptions(showSkill)); const matches = result.skills.filter((skill) => skill.name === name || skill.skillPath === name); if (!matches.length) throw new Error(`Skill not found: ${name}`); output(matches.length === 1 ? matches[0] : matches, showSkill.opts().json); });
const setSkill = options(skills.command("set <name>").requiredOption("--scope <scope>", "global or workspace").option("--disable", "disable the skill").option("--enable", "enable/reset the skill")).description("Set a skill override"); setSkill.action(async (name: string) => { const opts = discoveryOptions(setSkill); const result = await discoverSkills(opts); const skill = result.skills.find((item) => item.name === name || item.skillPath === name); if (!skill) throw new Error(`Skill not found: ${name}`); const scope = setSkill.opts().scope as "global" | "workspace"; const enabled = Boolean(setSkill.opts().enable); output(await setSkillEnabled(opts, skill.skillPath, scope, enabled), setSkill.opts().json); });
const mcps = program.command("mcp").alias("mcps").description("Inspect MCP servers");
const listMcp = options(mcps.command("list").description("List MCP servers")); listMcp.action(async () => { const result = await discoverMcps(discoveryOptions(listMcp)); output(result, listMcp.opts().json); });
const showMcp = options(mcps.command("show <name>").description("Show an MCP server")); showMcp.action(async (name: string) => { const result = await discoverMcps(discoveryOptions(showMcp)); const matches = result.mcps.filter((mcp) => mcp.name === name); if (!matches.length) throw new Error(`MCP not found: ${name}`); output(matches.length === 1 ? matches[0] : matches, showMcp.opts().json); });
const setMcp = options(mcps.command("set <name>").requiredOption("--scope <scope>", "global or workspace").option("--disable").option("--enable")).description("Set an MCP override"); setMcp.action(async (name: string) => { const values = setMcp.opts(); output(await setMcpState(discoveryOptions(setMcp), values.scope as "global" | "workspace", name, Boolean(values.enable)), values.json); });
const addMcp = options(mcps.command("add <name>").requiredOption("--scope <scope>", "global or workspace").requiredOption("--config <json>", "MCP config as JSON")).description("Add an MCP definition"); addMcp.action(async (name: string) => { const values = addMcp.opts(); output(await addMcpDefinition(discoveryOptions(addMcp), values.scope as "global" | "workspace", name, JSON.parse(values.config)), values.json); });
const updateMcp = options(mcps.command("update <name>").requiredOption("--scope <scope>", "global or workspace").requiredOption("--patch <json>", "MCP patch as JSON")).description("Update an MCP definition"); updateMcp.action(async (name: string) => { const values = updateMcp.opts(); output(await updateMcpDefinition(discoveryOptions(updateMcp), values.scope as "global" | "workspace", name, JSON.parse(values.patch)), values.json); });
const deleteMcp = options(mcps.command("delete <name>").requiredOption("--scope <scope>", "global or workspace")).description("Delete an MCP definition"); deleteMcp.action(async (name: string) => { const values = deleteMcp.opts(); output(await deleteMcpDefinition(discoveryOptions(deleteMcp), values.scope as "global" | "workspace", name), values.json); });
const tools = options(mcps.command("tools <name>").requiredOption("--scope <scope>", "global or workspace").description("Explicitly load MCP tools")); tools.action(async (name: string) => { const result = await discoverMcps(discoveryOptions(tools)); const mcp = result.mcps.find((item) => item.name === name && item.scope === tools.opts().scope); if (!mcp) throw new Error(`MCP not found: ${name}`); output(await loadMcpTools(mcp), tools.opts().json); });
const agents = program.command("agents").description("Inspect subagent TOML files");
const listAgents = options(agents.command("list").description("List discovered agents")); listAgents.action(async () => { output(await discoverAgents(discoveryOptions(listAgents)), listAgents.opts().json); });
const showAgent = options(agents.command("show <name>").description("Show an agent TOML file")); showAgent.action(async (name: string) => { const result = await discoverAgents(discoveryOptions(showAgent)); const matches = result.agents.filter((agent) => agent.name === name || agent.path === name); if (!matches.length) throw new Error(`Agent not found: ${name}`); output(matches.length === 1 ? matches[0] : matches, showAgent.opts().json); });

const resource = program.command("resource").description("Rename, delete, and transfer managed resources");
const renameResource = options(resource.command("rename <kind> <target> <newName>").description("Rename a skill, agent, or MCP")); renameResource.action(async (kind: string, target: string, newName: string) => { const opts = discoveryOptions(renameResource); if (kind === "skill") { const result = await discoverSkills(opts); const skill = result.skills.find((item) => item.skillPath === target || item.skillDirectory === target || item.name === target); if (!skill) throw new Error(`Skill not found: ${target}`); output(await renameSkill(opts, skill.skillDirectory, newName, Boolean(skill.plugin)), renameResource.opts().json); } else if (kind === "agent") { const result = await discoverAgents(opts); const agent = result.agents.find((item) => item.path === target || item.name === target); if (!agent) throw new Error(`Agent not found: ${target}`); output(await renameAgent(opts, agent.path, newName, Boolean(agent.readOnly)), renameResource.opts().json); } else if (kind === "mcp") { output(await renameMcpAcrossScopes(opts, target, newName), renameResource.opts().json); } else throw new Error(`Unsupported resource kind: ${kind}`); });
const deleteResourceCommand = options(resource.command("delete <kind> <target>").description("Delete a skill, agent, or MCP")); deleteResourceCommand.requiredOption("--scope <scope>", "global or workspace"); deleteResourceCommand.action(async (kind: string, target: string) => { const opts = discoveryOptions(deleteResourceCommand); const scope = deleteResourceCommand.opts().scope as "global" | "workspace"; let identity: ResourceIdentity;
  if (kind === "skill") { const result = await discoverSkills(opts); const item = result.skills.find((skill) => skill.skillPath === target || skill.skillDirectory === target || skill.name === target); if (!item) throw new Error(`Skill not found: ${target}`); identity = { kind: "skill", id: item.id, name: item.name, scope: item.scope, path: item.skillDirectory, relativePath: item.relativePath, sourceKind: item.sourceKind, readOnly: Boolean(item.plugin), plugin: item.plugin }; }
  else if (kind === "agent") { const result = await discoverAgents(opts); const item = result.agents.find((agent) => agent.path === target || agent.name === target); if (!item) throw new Error(`Agent not found: ${target}`); identity = { kind: "agent", id: item.id, name: item.name, scope: item.scope, path: item.path, relativePath: item.relativePath, sourceKind: item.sourceKind, readOnly: Boolean(item.readOnly) }; }
  else if (kind === "mcp") { const result = await discoverMcps(opts); const item = result.mcps.find((mcp) => mcp.name === target && mcp.scope === scope); if (!item) throw new Error(`MCP not found: ${target}`); identity = { kind: "mcp", id: item.id, name: item.name, scope: item.scope, path: item.configPath, sourceKind: item.sourceKind, readOnly: Boolean(item.readOnly), plugin: item.plugin }; }
  else throw new Error(`Unsupported resource kind: ${kind}`);
  output(await deleteResource(opts, identity), deleteResourceCommand.opts().json);
});
const transferResource = options(resource.command("transfer <kind> <target>").description("Copy or move a resource")); transferResource.requiredOption("--scope <scope>", "target global or workspace").requiredOption("--operation <operation>", "copy or move").option("--target-path <path>").option("--conflict <mode>", "skip, replace, or decide-each", "skip"); transferResource.action(async (kind: string, target: string) => { const opts = discoveryOptions(transferResource); const values = transferResource.opts(); const scope = values.scope as "global" | "workspace"; let resultIdentity: ResourceIdentity | undefined;
  if (kind === "skill") { const result = await discoverSkills(opts); const item = result.skills.find((skill) => skill.skillPath === target || skill.skillDirectory === target || skill.name === target); if (item) resultIdentity = { kind: "skill", id: item.id, name: item.name, scope: item.scope, path: item.skillDirectory, relativePath: item.relativePath, sourceKind: item.sourceKind, readOnly: Boolean(item.plugin), plugin: item.plugin }; }
  else if (kind === "agent") { const result = await discoverAgents(opts); const item = result.agents.find((agent) => agent.path === target || agent.name === target); if (item) resultIdentity = { kind: "agent", id: item.id, name: item.name, scope: item.scope, path: item.path, relativePath: item.relativePath, sourceKind: item.sourceKind, readOnly: Boolean(item.readOnly) }; }
  else if (kind === "mcp") { const result = await discoverMcps(opts); const item = result.mcps.find((mcp) => mcp.name === target); if (item) resultIdentity = { kind: "mcp", id: item.id, name: item.name, scope: item.scope, path: item.configPath, sourceKind: item.sourceKind, readOnly: Boolean(item.readOnly), plugin: item.plugin }; }
  if (!resultIdentity) throw new Error(`${kind} not found: ${target}`); output(await transferResources(opts, { resources: [resultIdentity], operation: values.operation as "copy" | "move", targetScope: scope, targetPath: values.targetPath, conflictMode: values.conflict as "skip" | "replace" | "decide-each" }), transferResource.opts().json);
});

program.parseAsync().catch((error: unknown) => { console.error(error instanceof Error ? error.message : String(error)); process.exitCode = 1; });
